name: vinance
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.5 <4.0.0"

dependencies:

  awesome_dialog: ^3.1.0
  bottom_navy_bar: ^6.0.0
  cached_network_image: ^3.3.0
  carousel_slider: ^4.2.1
  country_picker: ^2.0.23
  cupertino_icons: ^1.0.6
  custom_refresh_indicator: ^3.0.0
  dio: ^5.4.1
  dotted_border: ^2.1.0
  downloadsfolder: ^0.1.1
  equatable: ^2.0.5
  file_picker: ^8.0.0+1
  firebase_analytics: ^10.7.2
  firebase_auth: ^4.17.8
  firebase_core: ^2.27.0
  firebase_core_platform_interface: ^5.0.0
  firebase_messaging: ^14.7.19
  flutter:
    sdk: flutter
  flutter_inappwebview: ^6.0.0
  flutter_local_notifications: ^17.0.0
  flutter_rating_bar: ^4.0.1
  flutter_spinkit: ^5.2.0
  flutter_sticky_header: ^0.6.5
  flutter_svg: ^2.0.4
  flutter_widget_from_html: ^0.14.11
  flutter_xlider: ^3.5.0
  get: ^4.6.6
  google_sign_in: ^6.2.1
  http: ^1.2.0
  image_gallery_saver: ^2.0.3
  image_picker: ^1.0.7
  intl: ^0.19.0
  introduction_screen: ^3.1.12
  local_auth: ^2.1.8
  lottie: ^3.0.0
  path_provider: ^2.0.9
  permission_handler: ^11.1.0
  pin_code_fields: ^8.0.1
  pusher_channels_flutter: ^2.2.1
  qr_flutter: ^4.1.0
  share_plus: ^7.2.1
  shared_preferences: ^2.0.13
  shimmer: ^3.0.0
  simple_animations: ^5.0.2
  url_launcher: ^6.2.5
  vibration: ^1.8.4
  web3dart: ^2.7.3
  web3modal_flutter: ^3.1.1
  webview_flutter: ^4.7.0
  zoom_tap_animation: ^1.1.0
  open_file: ^3.3.2

dev_dependencies:
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/logo/
    - assets/images/background/
    - assets/icons/
    - assets/animation/
