// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCaGLvUfZY3XoYvju8iLK8MDD_p1HiQ-AA',
    appId: '1:342219345156:web:19f8f460357184399a9451',
    messagingSenderId: '342219345156',
    projectId: 'rexxtoria-427fe',
    authDomain: 'rexxtoria-427fe.firebaseapp.com',
    storageBucket: 'rexxtoria-427fe.appspot.com',
    measurementId: 'G-DWNVRM8L91',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCP0FIcm5usBC4igz6178NxKpdz6yica3s',
    appId: '1:342219345156:android:b68e2174e9dffb7c9a9451',
    messagingSenderId: '342219345156',
    projectId: 'rexxtoria-427fe',
    storageBucket: 'rexxtoria-427fe.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtJGlceGABeaL8C7lcXtOjr-UUUP9m4Es',
    appId: '1:342219345156:ios:9dda2482301831219a9451',
    messagingSenderId: '342219345156',
    projectId: 'rexxtoria-427fe',
    storageBucket: 'rexxtoria-427fe.appspot.com',
    iosBundleId: 'dev.vlab.vinance',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZ82qh5pUnGvUuXMA9oUn1ywItHfExTMk',
    appId: '1:678649964403:ios:20e5f7765752872d550706',
    messagingSenderId: '678649964403',
    projectId: 'vinance-project',
    storageBucket: 'vinance-project.appspot.com',
    iosBundleId: 'dev.vlab.vinance.RunnerTests',
  );
}